### ISSUE TITLE
encountering `KeyError: 'sensor_temperature_PCB'` when using DELFT_processing.py

### ISSUE THREAD

**Issue by saveriogzz** [ltelab/disdrodb#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi guys,
I'll start keeping public track of some of the common errors I encounter, I guess it will be useful in the future!

When running the `run_DELFT_processing.py` script on the files for the PAR002 instrument. I get a  `Key Error` when the program is trying to convert the parquet to netcdf file. Here is the log response:
```python
There are the following metadata files without corresponding data: ['PAR001']
 - L0 processing of station_id PAR002 has started.
 - 79 files to process in /home/sguzzo/Parsivel/RAW_TELEGRAM/CABAUW
 - 0 of 1 have been skipped.
 - Conversion to Apache Parquet started.
 - Conversion to Apache Parquet ended.
 - L0 processing of station_id PAR002 ended in 1.34s
 - L1 processing of station_id PAR002 has started.
 - Reading L0 Apache Parquet file at /home/sguzzo/Parsivel/Processed/CABAUW/L0/CABAUW_sPAR002_20211008.parquet started
 - Reading L0 Apache Parquet file at /home/sguzzo/Parsivel/Processed/CABAUW/L0/CABAUW_sPAR002_20211008.parquet ended
 - Retrieval of L1 data matrix started.
 - Retrieval of L1 data matrix finished.
Traceback (most recent call last):
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 504, in <module>
    main()
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 466, in main
    write_L1_to_netcdf(ds, fpath=fpath, sensor_name=sensor_name)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/L1_proc.py", line 319, in write_L1_to_netcdf
    encoding_dict = {k: encoding_dict[k] for k in ds.data_vars}
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/L1_proc.py", line 319, in <dictcomp>
    encoding_dict = {k: encoding_dict[k] for k in ds.data_vars}
KeyError: 'sensor_temperature_PCB'
```

### Steps To Reproduce

Example of raw data file that can be used to reproduce the error: [20211007.zip](https://github.com/ltelab/disdrodb/files/8262560/20211007.zip)

### What python version are you using?

3.9.*

**Comment by ghiggi** [comment]
Replace in the `parser_RASBERRY.py`  occurence of `sensor_temperature_PCB `with `sensor_temperature_pcb` .
Should solve the issue ;)

**Comment by saveriogzz** [comment]
> Replace in the `parser_RASBERRY.py` occurence of `sensor_temperature_PCB `with `sensor_temperature_pcb` . Should solve the issue ;)

That will give `KeyError: 'sensor_temperature_pcb'` ( I'm using the latest modifications on the main branch)

**Comment by saveriogzz** [comment]
Hey @ghiggi , here is the columns' names list I'm using

```python
column_names = ['rainfall_rate_32bit',
                    'rainfall_accumulated_32bit',
                    'weather_code_synop_4680',
                    'weather_code_synop_4677',
                    'weather_code_metar_4678',
                    'weather_code_nws',
                    'reflectivity_32bit',
                    'mor_visibility',
                    'sample_interval',
                    'laser_amplitude',
                    'number_particles',
                    'sensor_temperature',
                    'sensor_serial_number',
                    'firmware_iop',
                    'firmware_dsp',
                    'sensor_heating_current',
                    'sensor_battery_voltage',
                    'sensor_status',
                    'date_time_measurement_start',
                    'sensor_time',
                    'sensor_date',
                    'station_name',
                    'station_number',
                    'rainfall_amount_absolute_32bit',
                    'error_code',
                    'sensor_temperature_pcb',
                    'sensor_temperature_receiver',
                    'sensor_temperature_trasmitter',
                    'rainfall_rate_16bit_30',
                    'rainfall_rate_16bit_1200',
                    'rainfall_accumulated_16bit',
                    'reflectivity_16bit',
                    'rain_kinetic_energy',
                    'snowfall_rate',
                    'number_particles_all',
                    # 'list_particles',
                    'raw_drop_concentration',
                    'raw_drop_average_velocity',
                    'raw_drop_number',
                    ]
```

However, I still get the same error.

**Comment by saveriogzz** [comment]
The issue depended on having, in the yml metadata file for PAR001, the variable `sensor_name` defined as `OTT_Parsivel` instead of `OTT_Parsivel2`
